steps:
- id: 'Get Dependencies'
  name: 'gcr.io/cloud-builders/go'
  args: ['get', '-t', './...']
  env: ['PROJECT_ROOT=go-in-go']

- id: 'Run Test Suite'
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  env: ['PROJECT_ROOT=go-in-go']

- id: 'Install Binary'
  name: 'gcr.io/cloud-builders/go'
  args: ['install','.']
  env: ['PROJECT_ROOT=go-in-go']
